FROM nvcr.io/nvidia/l4t-cuda:12.6.11-runtime

WORKDIR /app

# install python
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip

# copy and install program dependencies
COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

# No entrypoint is needed, as the script will be runned with manual input